### ISSUE TITLE
Uninitialized pointers and seg fault

### ISSUE THREAD

**Issue by mabader** [acolijn/G4simu#2]
I'm having to potential bugs in the code:
-  \*  Break - segmentation violation\* when I exit the simulation
-  _'Member 'm_pSourceCore_PhysicalVolume was not initialized in this constructor'_. Error for all other Physical - and Logical Volume pointers in the DetectorConstruction.cc file

Is that something that occurs for you too?

**Comment by acolijn** [comment]
first: only an issue when running with 0 events in interactive mode. 
second: don't know.
